steps:
# Build the container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/automl-labeling-tool', '.']
# Push the container to GCR
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/automl-labeling-tool']
images:
- gcr.io/$PROJECT_ID/automl-labeling-tool
